### ISSUE TITLE
2.8.0-rc6

### ISSUE THREAD

**Issue by laapsaap** [sous-chefs/redisio#92]
Does this cookbook works with 2.8.0-rc6?   I changed google files download link to redis.io

[2013-11-15T15:42:43+00:00] WARN: Overridden Run List: [recipe[redisio::enable]]
Compiling Cookbooks...
# 
# Recipe Compile Error in /opt/cookbooks/redisio/recipes/enable.rb
## NoMethodError

undefined method `each' for nil:NilClass
